name: Daily GitHub Reforestation 🌳
on:
  schedule:
    - cron: "0 0,3,6,9,12,14,16 * * *"
  workflow_dispatch:

jobs:
  auto_commit:
    name: Pretending to be productive
    runs-on: ubuntu-latest
    steps:
      - name: Gaslighting Git into thinking this directory is safe
        run: git config --global --add safe.directory /github/workspace
      - uses: actions/checkout@v3     
        with:
          persist-credentials: true
          fetch-depth: 1
          
      - name: Calculate randomized execution delay
        id: random_data
        run: |
          SLEEP_TIME=$(( $RANDOM % 3600 ))
          echo "Sleeping for $SLEEP_TIME seconds..."
          sleep $SLEEP_TIME

          MESSAGES=(
            "I have no idea why this works"
            "another commit, another regret"
            "it works… don't touch it!"
            "just one more fix bro I swear"
            "+1 bug, +1 feature, perfectly balanced"
            "added feature nobody asked for"
            "why am I still doing this"
            "its 3am and im still coding send help!"
            "works on my machine ¯\_(ツ)_/¯"
            "I should've been a farmer"
          )

          RANDOM_MSG=${MESSAGES[$RANDOM % ${#MESSAGES[@]}]}
          echo "COMMIT_MSG=$RANDOM_MSG" >> $GITHUB_ENV

      - name: Update activity timestamp
        run: |
          cat > LAST_UPDATED
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo "Sync metadata: $d" > LAST_UPDATED
          
      - name: Generate randomized git contribution
        run: |
          git config --local user.email "linstrahl@gmail.com"
          git config --local user.name "linstrahl"
          git add -A
          git commit -m "${{ env.COMMIT_MSG }}"
          
      - name: Synchronize changes to Origin
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
